import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { StoreProvider } from './context/StoreProvider';
import Navbar from './components/Navbar';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Weather Explorer',
  description: 'Generated by Deepak Pal',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}><StoreProvider>
        <Navbar/>
        {children}
        </StoreProvider></body>
    </html>
  );
}
